<?php

/**
* Generated By GZeinNumerCodeGenerator
* www.github.com/gzeinnumer
* at 2023-02-28 17:03:56
* zip name 20230228170356_users_6D1WCL9Ywn.zip
*/

namespace App\Http\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

class UsersResource extends JsonResource
{
    /**
     *   new UsersResource(object)
     *   UsersResource::collection([])
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'email_verified_at' => $this->email_verified_at,
            'password' => $this->password,
            'remember_token' => $this->remember_token,
            'created_at' => Carbon::parse($this->created_at)->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::parse($this->updated_at)->format('Y-m-d H:i:s'),
        ];
    }
}
